RECETAS = [
    {
        "nombre": "Tortilla de papas",
        "descripcion": "La clásica tortilla española, jugosa por dentro y dorada por fuera.",
        "categoria": "Desayuno",
        "dificultad": "facil",
        "tiempo_minutos": 30,
        "porciones": 4,
        "color": "#E3A62F",
        "imagen": "tortilla-papas.jpg",
        "ingredientes": [
            "5 papas medianas",
            "6 huevos",
            "1 cebolla",
            "200 ml de aceite de oliva",
            "Sal a gusto",
        ],
        "pasos": [
            "Pelar y cortar las papas en láminas finas.",
            "Cortar la cebolla en juliana fina.",
            "Freír las papas y la cebolla en aceite a fuego medio hasta que estén tiernas.",
            "Escurrir el exceso de aceite y mezclar con los huevos batidos y sal.",
            "Cocinar en sartén caliente 4 minutos de cada lado hasta dorar.",
        ],
    },
    {
        "nombre": "Ensalada Caprese",
        "descripcion": "Tomate, mozzarella y albahaca fresca con un hilo de aceite de oliva.",
        "categoria": "Entrada",
        "dificultad": "facil",
        "tiempo_minutos": 10,
        "porciones": 2,
        "color": "#C1432E",
        "imagen": "ensalada-caprese.jpg",
        "ingredientes": [
            "3 tomates grandes",
            "250 g de mozzarella fresca",
            "Hojas de albahaca fresca",
            "Aceite de oliva extra virgen",
            "Sal y pimienta a gusto",
        ],
        "pasos": [
            "Cortar los tomates y la mozzarella en rodajas parejas.",
            "Alternar las rodajas de tomate y mozzarella en un plato.",
            "Repartir las hojas de albahaca por encima.",
            "Condimentar con aceite de oliva, sal y pimienta antes de servir.",
        ],
    },
    {
        "nombre": "Milanesa napolitana",
        "descripcion": "Milanesa crocante cubierta con salsa, jamón, queso y tomate gratinado.",
        "categoria": "Plato principal",
        "dificultad": "media",
        "tiempo_minutos": 40,
        "porciones": 4,
        "color": "#D4622B",
        "imagen": "milanesa-napolitana.jpg",
        "ingredientes": [
            "4 milanesas de carne",
            "4 fetas de jamón cocido",
            "4 fetas de queso mozzarella",
            "1 tomate en rodajas",
            "200 ml de salsa de tomate",
            "Orégano a gusto",
        ],
        "pasos": [
            "Freír las milanesas hasta dorar y colocarlas en una fuente.",
            "Cubrir cada una con salsa de tomate, jamón y queso.",
            "Agregar las rodajas de tomate por encima y espolvorear orégano.",
            "Gratinar en el horno hasta que el queso se derrita.",
            "Servir bien caliente, acompañada de papas fritas.",
        ],
    },
    {
        "nombre": "Pasta al pesto",
        "descripcion": "Fettuccine bañados en una salsa cremosa de albahaca, ajo y piñones.",
        "categoria": "Plato principal",
        "dificultad": "facil",
        "tiempo_minutos": 20,
        "porciones": 4,
        "color": "#52713F",
        "imagen": "pasta-pesto.jpg",
        "ingredientes": [
            "400 g de fettuccine",
            "2 tazas de hojas de albahaca",
            "50 g de piñones",
            "50 g de queso parmesano",
            "2 dientes de ajo",
            "100 ml de aceite de oliva",
        ],
        "pasos": [
            "Cocinar la pasta en agua con sal hasta que esté al dente.",
            "Procesar la albahaca, los piñones, el ajo, el parmesano y el aceite hasta obtener una salsa homogénea.",
            "Mezclar la pasta caliente con el pesto fuera del fuego.",
            "Servir con parmesano extra por encima.",
        ],
    },
    {
        "nombre": "Sopa de calabaza",
        "descripcion": "Crema suave y reconfortante, ideal para los días fríos.",
        "categoria": "Entrada",
        "dificultad": "facil",
        "tiempo_minutos": 35,
        "porciones": 4,
        "color": "#E0812F",
        "imagen": "sopa-calabaza.jpg",
        "ingredientes": [
            "1 kg de calabaza",
            "1 cebolla",
            "1 diente de ajo",
            "500 ml de caldo de verduras",
            "100 ml de crema de leche",
            "Sal, pimienta y nuez moscada a gusto",
        ],
        "pasos": [
            "Cortar la calabaza, la cebolla y el ajo en trozos.",
            "Cocinar todo en el caldo hasta que la calabaza esté tierna.",
            "Procesar hasta lograr una textura suave.",
            "Agregar la crema y condimentar con sal, pimienta y nuez moscada.",
            "Servir caliente con un chorrito de aceite de oliva.",
        ],
    },
    {
        "nombre": "Empanadas de carne",
        "descripcion": "Empanadas caseras rellenas de carne cortada a cuchillo y especias.",
        "categoria": "Plato principal",
        "dificultad": "dificil",
        "tiempo_minutos": 60,
        "porciones": 12,
        "color": "#B8793A",
        "imagen": "empanadas-carne.jpg",
        "ingredientes": [
            "12 tapas para empanadas",
            "500 g de carne picada a cuchillo",
            "2 cebollas",
            "1 morrón",
            "2 huevos duros",
            "Comino, pimentón y sal a gusto",
        ],
        "pasos": [
            "Rehogar la cebolla y el morrón picados hasta que estén transparentes.",
            "Agregar la carne y las especias, cocinar hasta que esté a punto.",
            "Dejar enfriar el relleno y añadir el huevo duro picado.",
            "Rellenar las tapas, cerrarlas con repulgue y llevarlas a horno fuerte.",
            "Hornear 15-20 minutos hasta que estén doradas.",
        ],
    },
    {
        "nombre": "Guacamole",
        "descripcion": "Palta pisada con tomate, cebolla y lima, para untar o acompañar.",
        "categoria": "Entrada",
        "dificultad": "facil",
        "tiempo_minutos": 15,
        "porciones": 4,
        "color": "#6B8E3F",
        "imagen": "guacamole.jpg",
        "ingredientes": [
            "3 paltas maduras",
            "1 tomate picado",
            "1/2 cebolla picada fina",
            "Jugo de 1 lima",
            "Cilantro fresco a gusto",
            "Sal y pimienta a gusto",
        ],
        "pasos": [
            "Pisar la pulpa de las paltas hasta lograr una pasta con textura.",
            "Incorporar el tomate, la cebolla y el cilantro picados.",
            "Agregar el jugo de lima, sal y pimienta y mezclar bien.",
            "Servir de inmediato con nachos o tostadas.",
        ],
    },
    {
        "nombre": "Tarta de manzana",
        "descripcion": "Tarta dulce con manzanas caramelizadas y un toque de canela.",
        "categoria": "Postre",
        "dificultad": "media",
        "tiempo_minutos": 50,
        "porciones": 8,
        "color": "#D9A441",
        "imagen": "tarta-manzana.jpg",
        "ingredientes": [
            "4 manzanas",
            "200 g de harina",
            "100 g de manteca",
            "100 g de azúcar",
            "2 huevos",
            "1 cdta de canela",
            "Mermelada de damasco para pincelar",
        ],
        "pasos": [
            "Preparar una masa con la harina, la manteca, el azúcar y los huevos.",
            "Estirarla y colocarla en un molde para tarta.",
            "Cortar las manzanas en láminas finas y disponerlas en forma de abanico.",
            "Espolvorear con canela y hornear 35-40 minutos.",
            "Pincelar con mermelada tibia al salir del horno para dar brillo.",
        ],
    },
    {
        "nombre": "Risotto de hongos",
        "descripcion": "Arroz cremoso cocido lentamente con hongos y parmesano.",
        "categoria": "Plato principal",
        "dificultad": "dificil",
        "tiempo_minutos": 45,
        "porciones": 4,
        "color": "#8A7B5C",
        "imagen": "risotto-hongos.jpg",
        "ingredientes": [
            "350 g de arroz arborio",
            "300 g de hongos mixtos",
            "1 cebolla picada",
            "1 litro de caldo de verduras caliente",
            "100 ml de vino blanco",
            "50 g de queso parmesano",
            "Manteca a gusto",
        ],
        "pasos": [
            "Saltear los hongos y reservar.",
            "Rehogar la cebolla, agregar el arroz y tostarlo un minuto.",
            "Añadir el vino y dejar que se evapore.",
            "Incorporar el caldo de a poco, revolviendo constantemente hasta que el arroz esté cremoso.",
            "Fuera del fuego, agregar los hongos, el parmesano y la manteca.",
        ],
    },
    {
        "nombre": "Smoothie bowl de frutos rojos",
        "descripcion": "Bowl cremoso de frutos rojos con granola, almendras y frutas frescas.",
        "categoria": "Desayuno",
        "dificultad": "facil",
        "tiempo_minutos": 10,
        "porciones": 1,
        "color": "#8B4B7F",
        "imagen": "smoothie-bowl.jpg",
        "ingredientes": [
            "1 taza de frutos rojos congelados",
            "1 banana congelada",
            "1/2 taza de yogur natural",
            "Granola a gusto",
            "Almendras a gusto",
            "Frutos rojos frescos para decorar",
        ],
        "pasos": [
            "Procesar los frutos rojos congelados, la banana y el yogur hasta obtener una crema espesa.",
            "Volcar en un bowl.",
            "Decorar con granola, almendras y frutos rojos frescos.",
            "Servir de inmediato con cuchara.",
        ],
    },
]
